"""
Generate printable portrait HTML cluster cards for the citizen workshop.

Each card shows:
- Cluster title (bilingual, no emoji)
- WORKS WELL section: 2-3 paired examples (photo + text from same report)
- PROBLEMS section: 2-3 paired examples (photo + text from same report)
- Layout adapts when one side dominates
- Designed for A4 or A3 portrait print

Run with:
    PYTHONPATH=src uv run python src/utils/generate_cluster_cards.py
"""

import base64
import os
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_distances

import os
from datetime import datetime
RUN_ID = os.environ.get("RUN_ID", datetime.now().strftime("%Y%m%d_%H%M"))

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

RESULTS_CSV    = "outputs/workshop_clusters.csv"
EMBEDDINGS_NPY = f"outputs/strategy2_fused_embeddings_50d_{RUN_ID}.npy"
OUTPUT_HTML    = "outputs/workshop_cluster_cards.html"

# Max paired examples per side
MAX_EXAMPLES_PER_SIDE = 3

# If one side has fewer than this many reports, show fewer examples
MIN_FOR_FULL = 3

CLUSTER_LABELS_CSV = "outputs/cluster_labels.csv"

def load_cluster_labels(csv_path: str) -> dict:
    """
    Load cluster labels from cluster_labels.csv generated by generate_cluster_labels.py.
    Falls back to cluster ID as label if file not found or column missing.
    Expected columns: cluster_id, label_de, label_en
    """
    try:
        df = pd.read_csv(csv_path)
        labels = {}
        for _, row in df.iterrows():
            cid = int(row["cluster_id"])
            labels[cid] = {
                "de": str(row.get("label_de", f"Cluster {cid}")).strip(),
                "en": str(row.get("label_en", f"Cluster {cid}")).strip(),
            }
        print(f"Loaded {len(labels)} cluster labels from {csv_path}")
        return labels
    except FileNotFoundError:
        print(f"[WARN] {csv_path} not found — using cluster IDs as labels.")
        print("       Run generate_cluster_labels.py first to generate labels.")
        return {}

CLUSTER_LABELS = load_cluster_labels(CLUSTER_LABELS_CSV)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def image_to_base64(filepath: str) -> str | None:
    try:
        with open(filepath, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")
    except Exception:
        return None


def get_diverse_pairs(
    subset_df: pd.DataFrame,
    subset_embs: np.ndarray,
    centroid: np.ndarray,
    max_examples: int,
) -> list:
    """
    Select a diverse set of complete report pairs (photo + text from same report).

    Strategy:
        - Pick 1 report closest to the centroid (most typical)
        - Pick remaining reports to maximise spread across the cluster
          using a greedy furthest-point selection — each new pick is
          the report furthest from all already-selected reports
        - Only considers reports with both a valid image AND text
        - Falls back to image-only if needed to fill slots

    This ensures the workshop card shows the range of what is in the
    cluster, not just multiple near-identical central examples.
    """
    if len(subset_df) == 0:
        return []

    # Filter to usable reports (image + text preferred)
    usable = []
    usable_embs = []
    for i, (_, row) in enumerate(subset_df.iterrows()):
        has_image = (
            pd.notna(row.get("local_image_path"))
            and os.path.exists(str(row.get("local_image_path", "")))
        )
        text = str(row.get("raw_text", "") or "").strip()
        has_text = text and text != "nan" and len(text) > 10
        if has_image and (has_text or len(usable) < max_examples):
            usable.append(row)
            usable_embs.append(subset_embs[i])

    if not usable:
        return []

    embs = np.array(usable_embs)

    # Start with the report closest to the centroid
    dists_to_centroid = cosine_distances(embs, centroid.reshape(1, -1)).flatten()
    first = int(np.argmin(dists_to_centroid))
    selected_indices = [first]

    # Greedily add the report furthest from all selected reports
    while len(selected_indices) < min(max_examples, len(usable)):
        selected_embs = embs[selected_indices]
        # For each candidate, find its minimum distance to any selected report
        min_dists = []
        for i in range(len(usable)):
            if i in selected_indices:
                min_dists.append(-1)  # already selected
                continue
            dists = cosine_distances(embs[i].reshape(1, -1), selected_embs).flatten()
            min_dists.append(float(np.min(dists)))
        next_pick = int(np.argmax(min_dists))
        selected_indices.append(next_pick)

    return [usable[i] for i in selected_indices]


# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

CSS = """
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    background: #e0e0e0;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
}

.card {
    width: 210mm;
    background: white;
    margin: 24px auto;
    padding: 28px 32px 32px;
    page-break-after: always;
}

/* ── Header ── */
.card-header {
    border-bottom: 4px solid #1a1a1a;
    padding-bottom: 14px;
    margin-bottom: 24px;
}

.cluster-number {
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: #999;
    margin-bottom: 5px;
}

.cluster-title-en {
    font-size: 28px;
    font-weight: 900;
    color: #1a1a1a;
    line-height: 1.1;
    letter-spacing: -0.01em;
}

.cluster-title-de {
    font-size: 15px;
    color: #555;
    font-weight: 400;
    margin-top: 4px;
}

.header-stats {
    display: flex;
    gap: 20px;
    margin-top: 10px;
    font-size: 12px;
    color: #666;
}

.stat-dot {
    display: inline-block;
    width: 8px; height: 8px;
    border-radius: 50%;
    margin-right: 5px;
    vertical-align: middle;
}

/* ── Section ── */
.section { margin-bottom: 24px; }

.section-header {
    font-size: 11px;
    font-weight: 800;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    padding: 7px 12px;
    border-radius: 4px;
    margin-bottom: 14px;
    display: flex;
    align-items: center;
    justify-content: space-between;
}

.section-good { background: #E2EFDA; color: #1A6B3A; }
.section-prob { background: #FCE4D6; color: #C00000; }

.section-count {
    font-size: 11px;
    font-weight: 600;
    opacity: 0.7;
}

/* ── Example row (paired photo + text) ── */
.example {
    display: flex;
    gap: 14px;
    margin-bottom: 12px;
    align-items: flex-start;
}

.example:last-child { margin-bottom: 0; }

.example-photo {
    flex-shrink: 0;
    width: 180px;
}

.example-photo img {
    width: 180px;
    height: 140px;
    object-fit: cover;
    border-radius: 4px;
    display: block;
}

.example-photo.no-image {
    width: 180px;
    height: 140px;
    background: #f0f0f0;
    border-radius: 4px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #bbb;
    font-size: 11px;
}

.example-text {
    flex: 1;
    padding-top: 2px;
}

.example-quote {
    font-size: 13px;
    line-height: 1.6;
    color: #222;
    font-style: italic;
}

.example-quote-good { border-left: 3px solid #5BB450; padding-left: 10px; }
.example-quote-prob { border-left: 3px solid #D94F37; padding-left: 10px; }


/* ── Empty state ── */
.empty { color: #bbb; font-size: 13px; font-style: italic; padding: 12px 0; }

/* ── Divider between sections ── */
.section-divider {
    border: none;
    border-top: 1.5px solid #e8e8e8;
    margin: 20px 0;
}

@media print {
    body { background: white; }
    .card { margin: 0; box-shadow: none; page-break-after: always; }
}
"""


# ---------------------------------------------------------------------------
# Card builder
# ---------------------------------------------------------------------------

def build_section(examples: list, side: str, n_total_side: int) -> str:
    header_class = "section-good" if side == "good" else "section-prob"
    quote_class  = "example-quote-good" if side == "good" else "example-quote-prob"
    label        = "Works Well" if side == "good" else "Problems"

    examples_html = ""

    if not examples:
        examples_html = '<div class="empty">No reports in this category.</div>'
    else:
        for row in examples:
            # Photo
            path = row.get("local_image_path", "")
            b64  = image_to_base64(str(path)) if pd.notna(path) else None

            if b64:
                photo_html = f'<img src="data:image/jpeg;base64,{b64}" alt="">'
                photo_div  = f'<div class="example-photo">{photo_html}</div>'
            else:
                photo_div  = '<div class="example-photo no-image">no photo</div>'

            # Text — use raw_text, fall back to topic
            text = str(row.get("raw_text", "") or "").strip()
            if not text or text == "nan":
                text = str(row.get("topic", "") or "").strip()
            if not text or text == "nan":
                text = "—"
            if len(text) > 240:
                text = text[:237] + "..."

            examples_html += f"""
            <div class="example">
                {photo_div}
                <div class="example-text">
                    <div class="example-quote {quote_class}">"{text}"</div>
                </div>
            </div>"""

    return f"""
    <div class="section">
        <div class="section-header {header_class}">
            <span>{label}</span>
            <span class="section-count">{n_total_side} reports</span>
        </div>
        {examples_html}
    </div>"""


def build_card_html(
    cluster_id: int,
    cluster_df: pd.DataFrame,
    embeddings: np.ndarray,
    centroid: np.ndarray,
) -> str:
    label   = CLUSTER_LABELS[cluster_id]
    n_total = len(cluster_df)
    n_good  = int((cluster_df["category"] == "works_well").sum())
    n_prob  = int((cluster_df["category"] == "problem").sum())

    # Adapt max examples based on dominance
    # If one side is small, show fewer examples from it
    def examples_for_side(n_side: int) -> int:
        if n_side == 0:   return 0
        if n_side <= 2:   return min(n_side, 1)
        if n_side <= 4:   return min(n_side, 2)
        return MAX_EXAMPLES_PER_SIDE

    # Get representative paired examples
    good_mask = cluster_df["category"] == "works_well"
    prob_mask = cluster_df["category"] == "problem"

    good_examples = get_diverse_pairs(
        cluster_df[good_mask].reset_index(drop=True),
        embeddings[good_mask.values],
        centroid,
        examples_for_side(n_good),
    )
    prob_examples = get_diverse_pairs(
        cluster_df[prob_mask].reset_index(drop=True),
        embeddings[prob_mask.values],
        centroid,
        examples_for_side(n_prob),
    )

    good_section = build_section(good_examples, "good", n_good)
    prob_section = build_section(prob_examples, "prob", n_prob)

    return f"""
    <div class="card">
        <div class="card-header">
            <div class="cluster-number">Cluster {cluster_id}</div>
            <div class="cluster-title-en">{label['en']}</div>
            <div class="cluster-title-de">{label['de']}</div>
            <div class="header-stats">
                <span><span class="stat-dot" style="background:#5BB450"></span>{n_good} works well</span>
                <span><span class="stat-dot" style="background:#D94F37"></span>{n_prob} problems</span>
                <span style="color:#aaa">{n_total} reports total</span>
            </div>
        </div>

        {good_section}
        <hr class="section-divider">
        {prob_section}
    </div>"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_cluster_cards(
    results_csv: str,
    embeddings_npy: str,
    output_html: str,
):
    print("Loading data...")
    df         = pd.read_csv(results_csv)
    embeddings = np.load(embeddings_npy)

    # Merge image paths and text
    llava = pd.read_csv("outputs/preprocessed_llava.csv")[
        ["photo_id", "raw_text", "local_image_path"]
    ]
    topics = pd.read_csv("data/raw/raw_data.csv")[["photo_id", "topic"]]

    df = df.merge(llava,   on="photo_id", how="left")
    df = df.merge(topics,  on="photo_id", how="left")

    print(f"Loaded {len(df)} reports.\n")

    cards_html = ""
    for cluster_id in sorted(df["hdbscan_label_assigned"].unique()):
        mask         = df["hdbscan_label_assigned"] == cluster_id
        cluster_df   = df[mask].reset_index(drop=True)
        cluster_embs = embeddings[mask.values]
        centroid     = cluster_embs.mean(axis=0)

        n_good = (cluster_df["category"] == "works_well").sum()
        n_prob = (cluster_df["category"] == "problem").sum()
        print(f"  Cluster {cluster_id}: {len(cluster_df)} reports ({n_good} good, {n_prob} problems)")

        cards_html += build_card_html(cluster_id, cluster_df, cluster_embs, centroid)

    html = f"""<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>MOVEO Workshop — Cluster Cards</title>
    <style>{CSS}</style>
</head>
<body>
{cards_html}
</body>
</html>"""

    with open(output_html, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"\nDone — {output_html}")
    print("Open in browser → Print → A4 portrait, no margins.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    generate_cluster_cards(
        results_csv    = RESULTS_CSV,
        embeddings_npy = EMBEDDINGS_NPY,
        output_html    = OUTPUT_HTML,
    )