import base64
import io
import os
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_distances

import os
from datetime import datetime
RUN_ID = os.environ.get("RUN_ID", datetime.now().strftime("%Y%m%d_%H%M"))
try:
    from staticmap import StaticMap, CircleMarker
    HAS_STATICMAP = True
except ImportError:
    HAS_STATICMAP = False
    print("Warning: staticmap not installed. Run: uv add staticmap")
    print("         Map snapshots will be skipped.\n")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

RESULTS_CSV    = "outputs/workshop_clusters.csv"
EMBEDDINGS_NPY = f"outputs/strategy2_fused_embeddings_50d_{RUN_ID}.npy"
OUTPUT_HTML    = "outputs/workshop_cluster_cards_with_map.html"
CLUSTER_LABELS_CSV = "outputs/cluster_labels.csv"

MAX_EXAMPLES_PER_SIDE = 3

TILE_URL          = "https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png"
MAP_WIDTH         = 1800
MAP_HEIGHT        = 750
WINTERTHUR_CENTER = (8.738563999520458, 47.497774499839835)
MAP_ZOOM          = 15

_DEFAULT_COLORS = [
    "#2E86AB", "#E84855", "#3BB273", "#F4A259", "#6A994E",
    "#7B2D8B", "#1D3461", "#F7B731", "#C1292E", "#00B4D8",
    "#E9C46A", "#F77F00",
]


# ---------------------------------------------------------------------------
# Load cluster labels from CSV
# ---------------------------------------------------------------------------

def load_cluster_labels(csv_path: str) -> dict:
    """
    Load cluster labels from cluster_labels.csv generated by generate_cluster_labels.py.
    Expected columns: cluster_id, label_de, label_en
    Falls back to cluster ID as label if file not found.
    """
    try:
        df = pd.read_csv(csv_path)
        labels = {}
        for _, row in df.iterrows():
            cid = int(row["cluster_id"])
            labels[cid] = {
                "de": str(row.get("label_de", f"Cluster {cid}")).strip(),
                "en": str(row.get("label_en", f"Cluster {cid}")).strip(),
            }
        print(f"Loaded {len(labels)} cluster labels from {csv_path}")
        return labels
    except FileNotFoundError:
        print(f"[WARN] {csv_path} not found — using cluster IDs as labels.")
        print("       Run generate_cluster_labels.py first to generate labels.")
        return {}


def build_cluster_colors(labels: dict) -> dict:
    colors = {}
    for i, cid in enumerate(sorted(labels.keys())):
        colors[cid] = _DEFAULT_COLORS[i % len(_DEFAULT_COLORS)]
    return colors


CLUSTER_LABELS = load_cluster_labels(CLUSTER_LABELS_CSV)
CLUSTER_COLORS = build_cluster_colors(CLUSTER_LABELS)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def image_to_base64(filepath: str) -> str | None:
    try:
        with open(filepath, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")
    except Exception:
        return None


def generate_cluster_map_image(
    cluster_df: pd.DataFrame,
    all_df: pd.DataFrame,
    cluster_id: int,
) -> str | None:
    if not HAS_STATICMAP:
        return None
    geo = cluster_df[cluster_df["lat"].notna() & cluster_df["long"].notna()]
    if geo.empty:
        return None
    m = StaticMap(MAP_WIDTH, MAP_HEIGHT, url_template=TILE_URL)
    other = all_df[
        (all_df["hdbscan_label_assigned"] != cluster_id)
        & all_df["lat"].notna()
        & all_df["long"].notna()
    ]
    for _, row in other.iterrows():
        m.add_marker(CircleMarker((float(row["long"]), float(row["lat"])), "#cccccc", 8))
    for _, row in geo.iterrows():
        fill = "#5BB450" if row.get("category") == "works_well" else "#D94F37"
        m.add_marker(CircleMarker((float(row["long"]), float(row["lat"])), fill, 14))
    try:
        image = m.render(zoom=MAP_ZOOM, center=WINTERTHUR_CENTER)
        buffer = io.BytesIO()
        image.save(buffer, format="PNG")
        return base64.b64encode(buffer.getvalue()).decode("utf-8")
    except Exception as e:
        print(f"    Map render failed for cluster {cluster_id}: {e}")
        return None


def get_diverse_pairs(
    subset_df: pd.DataFrame,
    subset_embs: np.ndarray,
    centroid: np.ndarray,
    max_examples: int,
) -> list:
    if len(subset_df) == 0:
        return []
    distances = cosine_distances(subset_embs, centroid.reshape(1, -1)).flatten()
    order     = np.argsort(distances)
    sorted_df = subset_df.iloc[order].reset_index(drop=True)
    complete = []
    for _, row in sorted_df.iterrows():
        if len(complete) >= max_examples:
            break
        has_image = (
            pd.notna(row.get("local_image_path"))
            and os.path.exists(str(row.get("local_image_path", "")))
        )
        text     = str(row.get("raw_text", "") or "").strip()
        has_text = text and text != "nan" and len(text) > 10
        if has_image and has_text:
            complete.append(row)
    if len(complete) < max_examples:
        for _, row in sorted_df.iterrows():
            if len(complete) >= max_examples:
                break
            if row["photo_id"] in [r["photo_id"] for r in complete]:
                continue
            has_image = (
                pd.notna(row.get("local_image_path"))
                and os.path.exists(str(row.get("local_image_path", "")))
            )
            if has_image:
                complete.append(row)
    return complete


# ---------------------------------------------------------------------------
# CSS
# ---------------------------------------------------------------------------

CSS = """
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
@page portrait-page  { size: A4 portrait; }
@page landscape-page { size: A4 landscape; }
body {
    font-family: 'Helvetica Neue', Arial, sans-serif;
    background: #e0e0e0;
    -webkit-print-color-adjust: exact;
    print-color-adjust: exact;
}
.card {
    width: 210mm;
    height: 297mm;
    overflow: hidden;
    background: white;
    margin: 24px auto;
    padding: 20px 24px;
    page-break-after: always;
    page: portrait-page;
}
.card-map {
    width: 297mm;
    height: 210mm;
    overflow: hidden;
    background: white;
    margin: 24px auto;
    padding: 20px 24px;
    page-break-after: always;
    page: landscape-page;
}
.card-header {
    border-bottom: 3px solid #1a1a1a;
    padding-bottom: 10px;
    margin-bottom: 14px;
}
.cluster-number {
    font-size: 11px; font-weight: 700; letter-spacing: 0.14em;
    text-transform: uppercase; color: #999; margin-bottom: 3px;
}
.cluster-title-en { font-size: 24px; font-weight: 900; color: #1a1a1a; line-height: 1.1; }
.cluster-title-de { font-size: 13px; color: #555; font-weight: 400; margin-top: 3px; }
.header-stats { display: flex; gap: 16px; margin-top: 8px; font-size: 11px; color: #666; }
.stat-dot {
    display: inline-block; width: 7px; height: 7px;
    border-radius: 50%; margin-right: 4px; vertical-align: middle;
}
.section { margin-bottom: 12px; }
.section-header {
    font-size: 10px; font-weight: 800; letter-spacing: 0.14em;
    text-transform: uppercase; padding: 5px 10px; border-radius: 3px;
    margin-bottom: 8px; display: flex; align-items: center; justify-content: space-between;
}
.section-good { background: #E2EFDA; color: #1A6B3A; }
.section-prob { background: #FCE4D6; color: #C00000; }
.section-count { font-size: 10px; font-weight: 600; opacity: 0.7; }
.example { display: flex; gap: 10px; margin-bottom: 8px; align-items: flex-start; }
.example:last-child { margin-bottom: 0; }
.example-photo { flex-shrink: 0; width: 160px; }
.example-photo img { width: 160px; height: 120px; object-fit: cover; border-radius: 3px; display: block; }
.example-photo.no-image {
    width: 160px; height: 120px; background: #f0f0f0; border-radius: 3px;
    display: flex; align-items: center; justify-content: center; color: #bbb; font-size: 10px;
}
.example-text { flex: 1; padding-top: 2px; }
.example-quote { font-size: 12px; line-height: 1.5; color: #222; font-style: italic; }
.example-quote-good { border-left: 3px solid #5BB450; padding-left: 8px; }
.example-quote-prob { border-left: 3px solid #D94F37; padding-left: 8px; }
.empty { color: #bbb; font-size: 12px; font-style: italic; padding: 8px 0; }
.section-divider { border: none; border-top: 1px solid #e8e8e8; margin: 10px 0; }
.map-page-body { display: flex; flex-direction: column; gap: 14px; }
.cluster-map { width: 100%; border-radius: 6px; overflow: hidden; border: 1px solid #e0e0e0; }
.cluster-map img { width: 100%; display: block; }
.cluster-map-legend {
    display: flex; gap: 18px; font-size: 11px; color: #555;
    padding: 6px 10px; background: #fafafa; border-top: 1px solid #efefef;
}
.map-legend-dot {
    display: inline-block; width: 9px; height: 9px;
    border-radius: 50%; margin-right: 5px; vertical-align: middle;
}
@media print {
    body { background: white; }
    .card, .card-map { margin: 0; box-shadow: none; page-break-after: always; }
}
"""


# ---------------------------------------------------------------------------
# Card builders
# ---------------------------------------------------------------------------

def build_header(cluster_id: int, n_good: int, n_prob: int, n_total: int) -> str:
    label = CLUSTER_LABELS.get(cluster_id, {"en": f"Cluster {cluster_id}", "de": f"Cluster {cluster_id}"})
    return f"""
    <div class="card-header">
        <div class="cluster-number">Cluster {cluster_id}</div>
        <div class="cluster-title-en">{label['en']}</div>
        <div class="cluster-title-de">{label['de']}</div>
        <div class="header-stats">
            <span><span class="stat-dot" style="background:#5BB450"></span>{n_good} works well</span>
            <span><span class="stat-dot" style="background:#D94F37"></span>{n_prob} problems</span>
            <span style="color:#aaa">{n_total} reports total</span>
        </div>
    </div>"""


def build_section(examples: list, side: str, n_total_side: int) -> str:
    header_class = "section-good" if side == "good" else "section-prob"
    quote_class  = "example-quote-good" if side == "good" else "example-quote-prob"
    label        = "Works Well" if side == "good" else "Problems"

    if not examples:
        examples_html = '<div class="empty">No reports in this category.</div>'
    else:
        examples_html = ""
        for row in examples:
            path = row.get("local_image_path", "")
            b64  = image_to_base64(str(path)) if pd.notna(path) else None
            if b64:
                photo_div = f'<div class="example-photo"><img src="data:image/jpeg;base64,{b64}" alt=""></div>'
            else:
                photo_div = '<div class="example-photo no-image">no photo</div>'
            text = str(row.get("raw_text", "") or "").strip()
            if not text or text == "nan":
                text = str(row.get("topic", "") or "").strip()
            if not text or text == "nan":
                text = "—"
            if len(text) > 160:
                text = text[:157] + "..."
            examples_html += f"""
            <div class="example">
                {photo_div}
                <div class="example-text">
                    <div class="example-quote {quote_class}">"{text}"</div>
                </div>
            </div>"""

    return f"""
    <div class="section">
        <div class="section-header {header_class}">
            <span>{label}</span>
            <span class="section-count">{n_total_side} reports</span>
        </div>
        {examples_html}
    </div>"""


def build_card_page1(
    cluster_id: int,
    cluster_df: pd.DataFrame,
    embeddings: np.ndarray,
    centroid: np.ndarray,
) -> str:
    n_total = len(cluster_df)
    n_good  = int((cluster_df["category"] == "works_well").sum())
    n_prob  = int((cluster_df["category"] == "problem").sum())

    def examples_for_side(n: int) -> int:
        if n == 0: return 0
        if n <= 2: return min(n, 1)
        if n <= 4: return min(n, 2)
        return MAX_EXAMPLES_PER_SIDE

    good_mask = cluster_df["category"] == "works_well"
    prob_mask = cluster_df["category"] == "problem"

    good_examples = get_diverse_pairs(
        cluster_df[good_mask].reset_index(drop=True),
        embeddings[good_mask.values], centroid, examples_for_side(n_good),
    )
    prob_examples = get_diverse_pairs(
        cluster_df[prob_mask].reset_index(drop=True),
        embeddings[prob_mask.values], centroid, examples_for_side(n_prob),
    )

    return f"""
    <div class="card">
        {build_header(cluster_id, n_good, n_prob, n_total)}
        {build_section(good_examples, "good", n_good)}
        <hr class="section-divider">
        {build_section(prob_examples, "prob", n_prob)}
    </div>"""


def build_card_page2(
    cluster_id: int,
    cluster_df: pd.DataFrame,
    all_df: pd.DataFrame,
) -> str:
    n_total = len(cluster_df)
    n_good  = int((cluster_df["category"] == "works_well").sum())
    n_prob  = int((cluster_df["category"] == "problem").sum())

    map_b64 = generate_cluster_map_image(cluster_df, all_df, cluster_id)
    if map_b64:
        map_html = f"""
        <div class="cluster-map">
            <img src="data:image/png;base64,{map_b64}" alt="Map of cluster {cluster_id}">
            <div class="cluster-map-legend">
                <span><span class="map-legend-dot" style="background:#5BB450"></span>Works well</span>
                <span><span class="map-legend-dot" style="background:#D94F37"></span>Problem</span>
                <span><span class="map-legend-dot" style="background:#cccccc"></span>Other clusters</span>
            </div>
        </div>"""
    else:
        map_html = '<div class="empty">No location data available for this cluster.</div>'

    return f"""
    <div class="card-map">
        {build_header(cluster_id, n_good, n_prob, n_total)}
        <div class="map-page-body">
            {map_html}
        </div>
    </div>"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_cluster_cards(
    results_csv: str,
    embeddings_npy: str,
    output_html: str,
):
    print("Loading data...")
    df         = pd.read_csv(results_csv)
    embeddings = np.load(embeddings_npy)

    llava  = pd.read_csv("outputs/preprocessed_llava.csv")[["photo_id", "raw_text", "local_image_path"]]
    topics = pd.read_csv("data/raw/raw_data.csv")[["photo_id", "topic"]]
    df = df.merge(llava,   on="photo_id", how="left")
    df = df.merge(topics,  on="photo_id", how="left")

    print(f"Loaded {len(df)} reports.\n")

    cards_html = ""
    for cluster_id in sorted(df["hdbscan_label_assigned"].unique()):
        mask         = df["hdbscan_label_assigned"] == cluster_id
        cluster_df   = df[mask].reset_index(drop=True)
        cluster_embs = embeddings[mask.values]
        centroid     = cluster_embs.mean(axis=0)

        n_good = (cluster_df["category"] == "works_well").sum()
        n_prob = (cluster_df["category"] == "problem").sum()
        print(f"  Cluster {cluster_id}: {len(cluster_df)} reports ({n_good} good, {n_prob} problems)")

        cards_html += build_card_page1(cluster_id, cluster_df, cluster_embs, centroid)
        cards_html += build_card_page2(cluster_id, cluster_df, df)

    html = f"""<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <title>MOVEO Workshop — Cluster Cards</title>
    <style>{CSS}</style>
</head>
<body>
{cards_html}
</body>
</html>"""

    with open(output_html, "w", encoding="utf-8") as f:
        f.write(html)

    n_clusters = len(df["hdbscan_label_assigned"].unique())
    print(f"\nDone — {output_html}")
    print(f"Total pages: {2 * n_clusters} (2 per cluster)")
    print("Open in browser → Print → A4, no margins.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    generate_cluster_cards(
        results_csv    = RESULTS_CSV,
        embeddings_npy = EMBEDDINGS_NPY,
        output_html    = OUTPUT_HTML,
    )