"""
Generate an interactive Folium map of all citizen reports with:
- Cluster layer toggles (individual + toggle all)
- Sentiment filter (works_well / problem / both)
- Photo popups with report text

Run with:
    PYTHONPATH=src uv run python src/utils/generate_workshop_map.py
"""

import base64
import os
import folium
import pandas as pd

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

RESULTS_CSV = "outputs/workshop_clusters.csv"
OUTPUT_HTML = "outputs/workshop_map.html"

CLUSTER_LABELS_CSV = "outputs/cluster_labels.csv"

def load_cluster_labels(csv_path: str) -> dict:
    """
    Load cluster labels from cluster_labels.csv generated by generate_cluster_labels.py.
    The map uses German labels (label_de column).
    Falls back to cluster ID as label if file not found.
    Expected columns: cluster_id, label_de, label_en
    """
    try:
        import pandas as pd
        df = pd.read_csv(csv_path)
        labels = {}
        for _, row in df.iterrows():
            cid = int(row["cluster_id"])
            labels[cid] = str(row.get("label_de", f"Cluster {cid}")).strip()
        print(f"Loaded {len(labels)} cluster labels from {csv_path}")
        return labels
    except FileNotFoundError:
        print(f"[WARN] {csv_path} not found — using cluster IDs as labels.")
        print("       Run generate_cluster_labels.py first to generate labels.")
        return {}

CLUSTER_LABELS = load_cluster_labels(CLUSTER_LABELS_CSV)

# Default colors for up to 12 clusters — extend if needed
_DEFAULT_COLORS = [
    "#2E86AB", "#E84855", "#3BB273", "#F4A259", "#6A994E",
    "#7B2D8B", "#1D3461", "#F7B731", "#C1292E", "#00B4D8",
    "#E9C46A", "#F77F00",
]

def build_cluster_colors(labels: dict) -> dict:
    """Assign a color to each cluster ID dynamically."""
    colors = {}
    for i, cid in enumerate(sorted(labels.keys())):
        colors[cid] = _DEFAULT_COLORS[i % len(_DEFAULT_COLORS)]
    return colors

CLUSTER_COLORS = build_cluster_colors(CLUSTER_LABELS)

MAP_CENTER = [47.4997, 8.7241]
MAP_ZOOM   = 14


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def image_to_base64(filepath: str) -> str | None:
    try:
        with open(filepath, "rb") as f:
            return base64.b64encode(f.read()).decode("utf-8")
    except Exception:
        return None


def make_popup(row: pd.Series, cluster_label: str, color: str) -> folium.Popup:
    img_html = ""
    path = row.get("local_image_path", "")
    if pd.notna(path) and os.path.exists(str(path)):
        b64 = image_to_base64(str(path))
        if b64:
            img_html = f'<img src="data:image/jpeg;base64,{b64}" style="width:240px;height:160px;object-fit:cover;border-radius:6px;margin-bottom:8px;display:block;">'

    text = str(row.get("raw_text", "") or "").strip()
    if not text or text == "nan":
        text = str(row.get("topic", "") or "—").strip()
    if len(text) > 200:
        text = text[:197] + "..."

    category  = row.get("category", "")
    cat_label = "✅ Works well" if category == "works_well" else "⚠️ Problem"
    cat_color = "#1A6B3A" if category == "works_well" else "#C00000"
    cat_bg    = "#E2EFDA" if category == "works_well" else "#FCE4D6"

    popup_html = f"""
    <div style="width:260px;font-family:'Helvetica Neue',Arial,sans-serif;">
        {img_html}
        <div style="font-size:11px;font-weight:700;letter-spacing:0.1em;
                    text-transform:uppercase;color:{color};margin-bottom:4px;">
            {cluster_label}
        </div>
        <div style="font-size:13px;line-height:1.5;color:#222;
                    font-style:italic;margin-bottom:8px;">
            "{text}"
        </div>
        <div style="display:inline-block;padding:3px 10px;border-radius:12px;
                    background:{cat_bg};color:{cat_color};
                    font-size:11px;font-weight:600;">
            {cat_label}
        </div>
    </div>"""

    return folium.Popup(popup_html, max_width=280)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate_map(results_csv: str, output_html: str):
    print("Loading data...")
    df = pd.read_csv(results_csv)

    llava  = pd.read_csv("outputs/preprocessed_llava.csv")[["photo_id", "raw_text", "local_image_path"]]
    topics = pd.read_csv("data/raw/raw_data.csv")[["photo_id", "topic"]]
    df = df.merge(llava,  on="photo_id", how="left")
    df = df.merge(topics, on="photo_id", how="left")

    before = len(df)
    df = df[df["lat"].notna() & df["long"].notna()].reset_index(drop=True)
    print(f"  {before - len(df)} reports excluded (no coordinates)")
    print(f"  {len(df)} reports on map\n")

    # ── Build map ────────────────────────────────────────────────────────────
    m = folium.Map(location=MAP_CENTER, zoom_start=MAP_ZOOM, tiles="CartoDB positron")

    # Store all markers as GeoJSON so JS can filter them
    # We embed all markers directly and use JS to show/hide by data attributes
    # Each marker gets data-cluster and data-category attributes

    # Build one FeatureGroup per cluster
    groups = {}
    for cluster_id in sorted(df["hdbscan_label_assigned"].unique()):
        label = CLUSTER_LABELS.get(cluster_id, f"Cluster {cluster_id}")
        color = CLUSTER_COLORS.get(cluster_id, "#888")
        group = folium.FeatureGroup(
            name=f'<span style="color:{color}">⬤</span>&nbsp;{label}',
            show=True,
        )
        cluster_df = df[df["hdbscan_label_assigned"] == cluster_id]
        for _, row in cluster_df.iterrows():
            popup   = make_popup(row, label, color)
            tooltip = f"{label} — {'✅' if row['category'] == 'works_well' else '⚠️'}"
            folium.CircleMarker(
                location=[row["lat"], row["long"]],
                radius=8,
                color="white",
                weight=1.5,
                fill=True,
                fill_color=color,
                fill_opacity=0.85,
                popup=popup,
                tooltip=tooltip,
            ).add_to(group)
        group.add_to(m)
        groups[cluster_id] = group
        n = len(cluster_df)
        print(f"  Cluster {cluster_id} ({label}): {n} markers")

    folium.LayerControl(collapsed=False).add_to(m)

    # ── Legend ───────────────────────────────────────────────────────────────
    legend_items = ""
    for cid, label in CLUSTER_LABELS.items():
        color = CLUSTER_COLORS.get(cid, "#888")
        count = len(df[df["hdbscan_label_assigned"] == cid])
        legend_items += f"""
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:5px;">
            <div style="width:11px;height:11px;border-radius:50%;background:{color};flex-shrink:0;"></div>
            <div style="font-size:12px;color:#333;">{label}
                <span style="color:#999;font-size:11px;">({count})</span>
            </div>
        </div>"""

    legend_html = f"""
    <div id="map-legend" style="position:fixed;bottom:30px;left:30px;z-index:1000;
                background:white;padding:14px 18px;border-radius:8px;
                box-shadow:0 2px 8px rgba(0,0,0,0.15);
                font-family:'Helvetica Neue',Arial,sans-serif;min-width:220px;">
        <div style="font-size:11px;font-weight:700;margin-bottom:10px;
                    letter-spacing:0.1em;text-transform:uppercase;color:#444;">
            MOVEO Clusters
        </div>
        {legend_items}
    </div>"""

    m.get_root().html.add_child(folium.Element(legend_html))

    # ── Filter panel (sentiment + toggle all) ────────────────────────────────
    # We inject a custom HTML control panel and JS that manipulates
    # Leaflet layer visibility directly.

    n_good = len(df[df["category"] == "works_well"])
    n_prob = len(df[df["category"] == "problem"])

    filter_html = f"""
    <div id="filter-panel" style="
        position:fixed;top:20px;left:50%;transform:translateX(-50%);
        z-index:2000;background:white;padding:12px 20px;
        border-radius:8px;box-shadow:0 2px 12px rgba(0,0,0,0.18);
        font-family:'Helvetica Neue',Arial,sans-serif;
        display:flex;align-items:center;gap:16px;flex-wrap:wrap;">

        <!-- Sentiment filter -->
        <div style="font-size:11px;font-weight:700;letter-spacing:0.1em;
                    text-transform:uppercase;color:#666;">
            Show:
        </div>
        <div style="display:flex;gap:6px;">
            <button onclick="setSentiment('all')" id="btn-all"
                style="padding:5px 14px;border-radius:20px;border:none;cursor:pointer;
                       font-size:12px;font-weight:600;background:#1F4E79;color:white;">
                All ({len(df)})
            </button>
            <button onclick="setSentiment('works_well')" id="btn-good"
                style="padding:5px 14px;border-radius:20px;border:1.5px solid #3BB273;
                       cursor:pointer;font-size:12px;font-weight:600;
                       background:white;color:#1A6B3A;">
                ✅ Works well ({n_good})
            </button>
            <button onclick="setSentiment('problem')" id="btn-prob"
                style="padding:5px 14px;border-radius:20px;border:1.5px solid #E84855;
                       cursor:pointer;font-size:12px;font-weight:600;
                       background:white;color:#C00000;">
                ⚠️ Problems ({n_prob})
            </button>
        </div>

        <!-- Divider -->
        <div style="width:1px;height:24px;background:#e0e0e0;"></div>

        <!-- Toggle all clusters -->
        <button onclick="toggleAllClusters()" id="btn-toggle-all"
            style="padding:5px 14px;border-radius:20px;border:1.5px solid #1F4E79;
                   cursor:pointer;font-size:12px;font-weight:600;
                   background:white;color:#1F4E79;">
            Hide all clusters
        </button>
    </div>"""

    m.get_root().html.add_child(folium.Element(filter_html))

    # ── JavaScript for filtering ─────────────────────────────────────────────
    # Strategy: rebuild markers on the map filtered by sentiment.
    # We store all marker data in a JS array and re-render on filter change.
    # For cluster toggling we use the existing Leaflet layer control checkboxes.

    marker_data = []
    for _, row in df.iterrows():
        path = row.get("local_image_path", "")
        b64  = image_to_base64(str(path)) if pd.notna(path) and os.path.exists(str(path)) else None
        text = str(row.get("raw_text", "") or row.get("topic", "") or "").strip()
        if text == "nan": text = "—"
        if len(text) > 200: text = text[:197] + "..."
        marker_data.append({
            "lat":      float(row["lat"]),
            "lng":      float(row["long"]),
            "cluster":  int(row["hdbscan_label_assigned"]),
            "category": str(row.get("category", "")),
            "text":     text.replace('"', '&quot;').replace("'", "&#39;"),
            "img":      b64 or "",
        })

    cluster_colors_js  = str(CLUSTER_COLORS).replace("'", '"')
    cluster_labels_js  = str({str(k): v for k, v in CLUSTER_LABELS.items()}).replace("'", '"')

    js = f"""
    <script>
    // ── Data ──────────────────────────────────────────────────────────────
    var allMarkers = {marker_data};
    var clusterColors = {cluster_colors_js};
    var clusterLabels = {cluster_labels_js};
    var currentSentiment = 'all';
    var clustersVisible = true;
    var markerLayers = [];

    // ── Initialise markers ────────────────────────────────────────────────
    function initMarkers() {{
        // Remove existing dynamic markers
        markerLayers.forEach(function(l) {{ window._map.removeLayer(l); }});
        markerLayers = [];

        allMarkers.forEach(function(d) {{
            if (currentSentiment !== 'all' && d.category !== currentSentiment) return;

            var color = clusterColors[d.cluster] || '#888';
            var label = clusterLabels[String(d.cluster)] || 'Cluster ' + d.cluster;
            var catLabel = d.category === 'works_well' ? '✅ Works well' : '⚠️ Problem';
            var catColor = d.category === 'works_well' ? '#1A6B3A' : '#C00000';
            var catBg    = d.category === 'works_well' ? '#E2EFDA' : '#FCE4D6';
            var imgHtml  = d.img
                ? '<img src="data:image/jpeg;base64,' + d.img + '" style="width:240px;height:160px;object-fit:cover;border-radius:6px;margin-bottom:8px;display:block;">'
                : '';

            var popupHtml = '<div style="width:260px;font-family:Helvetica Neue,Arial,sans-serif;">'
                + imgHtml
                + '<div style="font-size:11px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;color:' + color + ';margin-bottom:4px;">' + label + '</div>'
                + '<div style="font-size:13px;line-height:1.5;color:#222;font-style:italic;margin-bottom:8px;">&ldquo;' + d.text + '&rdquo;</div>'
                + '<div style="display:inline-block;padding:3px 10px;border-radius:12px;background:' + catBg + ';color:' + catColor + ';font-size:11px;font-weight:600;">' + catLabel + '</div>'
                + '</div>';

            var marker = L.circleMarker([d.lat, d.lng], {{
                radius: 8,
                color: 'white',
                weight: 1.5,
                fillColor: color,
                fillOpacity: 0.85,
            }}).bindPopup(popupHtml, {{maxWidth: 280}})
              .bindTooltip(label + ' — ' + catLabel);

            marker.clusterid = d.cluster;
            marker.addTo(window._map);
            markerLayers.push(marker);
        }});
    }}

    // ── Sentiment filter ─────────────────────────────────────────────────
    function setSentiment(val) {{
        currentSentiment = val;

        // Update button styles
        var btns = {{'all': 'btn-all', 'works_well': 'btn-good', 'problem': 'btn-prob'}};
        Object.keys(btns).forEach(function(k) {{
            var btn = document.getElementById(btns[k]);
            if (k === val) {{
                btn.style.background = k === 'works_well' ? '#3BB273' : k === 'problem' ? '#E84855' : '#1F4E79';
                btn.style.color = 'white';
                btn.style.border = 'none';
            }} else {{
                btn.style.background = 'white';
                btn.style.color = k === 'works_well' ? '#1A6B3A' : k === 'problem' ? '#C00000' : '#1F4E79';
                btn.style.border = '1.5px solid ' + (k === 'works_well' ? '#3BB273' : k === 'problem' ? '#E84855' : '#1F4E79');
            }}
        }});

        initMarkers();
    }}

    // ── Toggle all clusters ───────────────────────────────────────────────
    function toggleAllClusters() {{
        clustersVisible = !clustersVisible;
        var btn = document.getElementById('btn-toggle-all');
        btn.textContent = clustersVisible ? 'Hide all clusters' : 'Show all clusters';
        btn.style.background = clustersVisible ? 'white' : '#1F4E79';
        btn.style.color = clustersVisible ? '#1F4E79' : 'white';

        // Toggle all Leaflet layer control checkboxes
        var checkboxes = document.querySelectorAll('.leaflet-control-layers-overlays input[type=checkbox]');
        checkboxes.forEach(function(cb) {{
            if (cb.checked !== clustersVisible) cb.click();
        }});
    }}

    // ── Wait for map to be ready then get reference ───────────────────────
    document.addEventListener('DOMContentLoaded', function() {{
        // Leaflet stores the map instance on the container div
        var mapDiv = document.getElementById('map');
        if (mapDiv && mapDiv._leaflet_id) {{
            window._map = window[Object.keys(window).find(k => window[k] && window[k]._container === mapDiv)];
        }}
        // Fallback: grab from leaflet internals
        setTimeout(function() {{
            var maps = [];
            for (var key in window) {{
                try {{
                    if (window[key] instanceof L.Map) maps.push(window[key]);
                }} catch(e) {{}}
            }}
            if (maps.length > 0) window._map = maps[0];
        }}, 500);
    }});
    </script>"""

    m.get_root().html.add_child(folium.Element(js))

    m.save(output_html)
    print(f"\nMap saved to {output_html}")
    print("Open in browser to explore.")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    generate_map(
        results_csv = RESULTS_CSV,
        output_html = OUTPUT_HTML,
    )